### ISSUE TITLE
Treecapitator

### ISSUE THREAD

**Issue by fugufish** [EnderMediaDev/The-1.7.10-Pack#852] opened 2015-08-26 04:21 UTC
Treecapitator works fine locally. On a remote server it has the effect of causing it to take a long time to cut a tree at its root, but not actually cutting the entire tree.

I tried disabling it in the config and the slow chop is still in effect. This is a fresh install.

**Comment by xJon** [comment] 2015-08-26 05:11
What tree doesn't it cut completely?
Can you provide an image or a short video?

**Comment by fugufish** [comment] 2015-08-26 14:23
vanilla spruce. unfortunately I'm not set up to do that. if I cut at the root log, it is as slow as if Treecapitator is working. I've tried tweaking the settings, disabling etc. but the slowness stays.

**Comment by fugufish** [comment] 2015-08-26 14:25
also, while the chopping is slow, the damage to the axe is only single block damage, so my guess is whatever function destroys the tree and damages the axes is just not triggering

**Comment by fugufish** [comment] 2015-08-26 14:51
Interestingly the disable treecapitator config took this morning, now I can't re enable it. I'm unsure why.

**Comment by xJon** [comment] 2015-08-26 21:01
Tested on client & server, unable to reproduce. It's working perfectly fine.
Closing this one!

**Closed by xJon** 2015-08-26 21:01 UTC
Labels: can't reproduce
