### ISSUE TITLE
Modpack Won't Start!

### ISSUE THREAD

**Issue by challenger1** [EnderMediaDev/The-1.7.10-Pack#814] opened 2015-08-03 15:32 UTC
When I first download the modpack, everything will download fine. Then when the playing window opens, them modpack will just sit there and load. There is never any progress shown on the progress bar, nor anywhere else. It also never crashes, providing me with very little information. I am not using Optifine, have java 1.7 64Gb with 4Gb of RAM. I have tried both reinstalling the modpack and trying it on another computer with the same java settings.
Here is a copy of the latest log: http://paste.ubuntu.com/11993751/
I have the .technic log available upon request. 
Thanks so much!

**Comment by xJon** [comment] 2015-08-03 20:11
Can you post here the latest-client-fml.log? this is not it :)

**Comment by challenger1** [comment] 2015-08-03 23:12
Yeah, sorry. Here it is: http://paste.ubuntu.com/11996561/

**Comment by xJon** [comment] 2015-08-04 08:54
The log shows a really normal loading process.
Try to start the modpack and give it 5 minutes to load. Maybe more.
It should be fine :)

**Comment by challenger1** [comment] 2015-08-04 13:17
I've given it an hour to load, but still nothing will happen on any of my computers.

**Comment by xJon** [comment] 2015-08-04 14:16
Can you give me your latest client log of the "1 hour loading"?

**Comment by challenger1** [comment] 2015-08-04 15:13
So while I was getting the log, I noticed it only lasted 10 minutes on the log, and that, at the end, it said that it ran out of memory and quit loading. That's probably the cause, but I don't know what I should do. I'm going to try allocating more space, but here it is anyways: http://paste.ubuntu.com/12000660/

**Comment by challenger1** [comment] 2015-08-04 16:01
I just realized that last post was the fml-client-3.log, sorry. And since I tried allocating more space, I don't have a copy of the 1 hour log, but here is one that lasts 15 minutes. There are also some places it says java.lang.OutOfMemoryError, so here it is: https://www.dropbox.com/s/q1hmbw8byp1dnbg/fml-client-latest.log?dl=0

**Comment by xJon** [comment] 2015-08-04 16:43
The first log is enough, it's indeed a memory issues. The pack loads and when it doesn't get anymore memory it just stops.
How much RAM do you have installed on your computer?

**Comment by challenger1** [comment] 2015-08-04 19:05
I had 4gb, but then tried 5GB and got the same result

**Comment by challenger1** [comment] 2015-08-04 19:22
Just tried it with 6 Gb, but it crashed with java.lang.OutOfMemoryError as the cause. Trying with max RAM-- 7GB

**Comment by challenger1** [comment] 2015-08-04 19:37
Even 7GB crashes: http://paste.ubuntu.com/12002310/

**Comment by xJon** [comment] 2015-08-04 20:10
Never use more than needed RAM. Set it to 3GB, or 3.5GB, and give me the log after 10+ minutes of loading.

**Comment by challenger1** [comment] 2015-08-04 21:12
I don't know how to find how much RAM I have, but if that means how much is in the local disk, (C:) then I have 374GB out of 687GB free.
Anyways, I tried it with 3.5GB and it ran out of memory

**Comment by challenger1** [comment] 2015-08-04 21:23
I tried it with 3GB and it also ran out of memory:
https://www.dropbox.com/s/q1hmbw8byp1dnbg/fml-client-latest.log?dl=0

**Comment by xJon** [comment] 2015-08-04 23:04
Right click "This PC" and go to "Properties", there, next to "Installed Memory", you can see the amount of RAM that you have.

**Comment by challenger1** [comment] 2015-08-04 23:15
OK, I have 8GB installed

**Comment by xJon** [comment] 2015-08-04 23:33
Maybe some setting limits the max RAM you can allocate.
> Right click on "This PC" -> choose "Properties" -> then on the left, click "Advanced system settings" -> then in the "Advanced" tab click "Environment Variables". Then scroll down on "System variables" to see if you have anything related to Java. If so, tell what it is.

**Comment by challenger1** [comment] 2015-08-05 00:27
The only thing there is JAVA_HOME

**Comment by Jardyn** [comment] 2015-08-05 00:28
Also, what programs do you have running when you're starting your game? It's possible the other programs are taking up the ram, causing you to not have enough to reserve for Java.

**Comment by challenger1** [comment] 2015-08-05 00:42
As soon as I noticed it taking a while loading I stopped all other programs and only had the launcher up and never started the launcher with something else up.

**Comment by Jardyn** [comment] 2015-08-05 03:46
So two ideas that I have, (not entirely sure about either one but just what I've thought up as possibilities so far) is that while it is a problem with the pack running out of ram, that might not be the root cause.

My line of thinking is that possibly one of the mods is generating a TON of errors during load up, and eating ram that way. Again that might be completely off the mark and have nothing to do with this, but if you get bored and want to try something, you might try going to your modpack folder, going to the mods sub folder, and dragging out Flans mod and copying it onto your desktop till you test it. ( I say Flans because I poked through one of the logs and saw a very large number of errors concerning that mod.)

You might also try booting up the mod pack without Applied Energistics 2.

If you do decide to try either of these things, remember to check and see if you have any other mods that rely on either flans mod or applied energistics and removing them temporarily as well.

Again, I'm not very certain about either of these two ideas, for all I know those errors concerning Flans could be entirely normal with that mod.

Good luck!

**Comment by xJon** [comment] 2015-08-05 09:42
@challenger1 What is the value of this "JAVA_HOME"?

**Comment by challenger1** [comment] 2015-08-05 12:47
It says the value of JAVA_HOME is C:\Program Files\Java\jdk1.7.0_11

Another important thing: I was about to try what Jardyn suggested: removing some mods and trying it then. So I took them out and noticed that the modpack said an update was available. No surprise. However, I looked in the upper right hand corner and saw that it said my installed version was 0.7.9e, not 0.7.9f, the latest version. So I selected the latest version and hit play to see what would happen. My computer crashed, although, I did have a few other things up. Anyways, I'm going to try just the 0.7.9f version, then try what Jardyn suggested. See ya back with results!

**Comment by challenger1** [comment] 2015-08-05 12:51
Well apparently, the whole technic platform reset so I don't have any of the modpacks installed. But there is still their files and folders in the .technic folder, but I still have to reinstall all of them. Just an FYI in case that affects something.

**Comment by xJon** [comment] 2015-08-05 13:47
Maybe you should try to reinstall something.
Obviously the modpack can run perfectly fine with 3GB, and if you have 8 installed you should be able to play. Maybe the launcher god confused.

**Comment by challenger1** [comment] 2015-08-05 15:01
So I tried removing the mods but it still ran out of memory. I'm gonna try reinstalling

**Comment by Jardyn** [comment] 2015-08-05 17:57
You might also try running just the vanilla game through the technic launcher. Also, do other modpacks work with the launcher is it just 1.7.10?

If you can't get vanilla to work through the launcher you might also try running the vanilla game, without even the launcher.

**Comment by challenger1** [comment] 2015-08-06 03:42
Alrighty! Update time! So I tried removing all of the mods and re-adding them in small groups. I noticed that projectred mod would make it crash and say: http://paste.ubuntu.com/12011342/. 
Some other modpacks work, but especially the bigger ones run out of memory. I haven't tried just the vanilla game through the launcher, but will probably get to that tomorrow. Thanks for all the help guys!

**Comment by challenger1** [comment] 2015-08-06 13:32
So when adding modpacks in small groups, when I get to refined relocation (adding them alphabetically) with thaumcraft, thermal dynamics, thermal expansion, and thermal foundation included, since they are required for other mods, it runs out of memory. However, this is about 215MB alone in the mods folder

**Comment by Jardyn** [comment] 2015-08-06 13:37
So it doesn't start crashing untill you add those four mods?

**Comment by challenger1** [comment] 2015-08-06 13:41
It crashes when I get to about 215MB, its just that I need those mods since I'm adding the mods alphabetically

**Comment by challenger1** [comment] 2015-08-06 13:42
But it does start crashing if I add the project red mods, but its not because of a memory issue. *See crash report above*

**Comment by Jardyn** [comment] 2015-08-06 13:53
Before the crashes first started, do you remember if anything updated?

**Comment by challenger1** [comment] 2015-08-06 13:58
No, nothing did. I hadn't played on 1.7.10 before, and my brother found it and said it had a good server, so I got it on the current computer and played it for the first time, and it ran out of memory. The last thing that updated was a custom modpack that I made using the technic launcher called Tech Storm, but I doubt that would affect the 1.7.10 pack.

**Comment by Jardyn** [comment] 2015-08-06 14:07
Mind humoring me for a bit?

Go to here https://webchat.freenode.net/ and under the channel type #tehelp

Figure that'll be a bit easier than the game of forum-post ping-pong.

**Comment by Jardyn** [comment] 2015-08-06 19:07
Alright, the problem has been solved, the final run time of this trouble shooting session is about 6 hours.

In the end, and this is just for future reference, for those who might have this problem, the defining points of the error were these two lines


java.lang.NoClassDefFoundError: Could not initialize class mrtjp.projectred.integration.RenderGate$

and

	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -XX:MaxPermSize=256m -XX:PermSize=256M -Xmx1g -Xms1g

I'm not entirely sure about ALL the details of the error, but the thing to notice is that under the listed JVM flags it has -Xmx defined twice. What's happening is javas default environment variables are conflicting with the arguments set by the technic launcher.

The way to fix this is, you go into the start bar and perform a search for "Edit Environment Variables," find the variable _JAVA_OPTIONS and delete it all together.

Again, this may not work for all cases, but it's what solved this iteration of the error.

**Comment by xJon** [comment] 2015-08-06 19:47
@Jardyn I figured it might be it, see [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/issues/814#issuecomment-127796511) comment of mine.
Some people have random allocation limits set, so they can't put all of their 4GB.

**Comment by Jardyn** [comment] 2015-08-06 20:05
Well, it took six  hours but now I know something more than I did earlier. So that's a plus

**Comment by Jardyn** [comment] 2015-08-09 16:51
Just letting you know that this one is solved, so you can go ahead and close it. I Apologize for the double post.

**Comment by xJon** [comment] 2015-08-09 18:07
:)

**Closed** 2015-08-09 18:07 UTC
Labels: help wanted
